# Generated by Django 4.2.16 on 2024-11-27 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
