# Generated by Django 4.2.16 on 2024-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="range_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="range_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
