# Generated by Django 4.2.16 on 2024-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0007_documentversion"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["-version_number"], name="editor_docu_version_0d0a95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["document", "-version_number"],
                name="editor_docu_documen_ea9bf5_idx",
            ),
        ),
    ]
