# Generated by Django 4.2.16 on 2024-12-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0008_documentversion_editor_docu_version_0d0a95_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentversion", name="editor_docu_version_0d0a95_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentversion", name="editor_docu_documen_ea9bf5_idx",
        ),
    ]
