# Generated by Django 4.2.16 on 2024-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "editor",
            "0009_remove_documentversion_editor_docu_version_0d0a95_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="crdt_metadata",
            field=models.JSONField(default=dict),
        ),
    ]
